name : A Basic Workflow

on:
  push:
    branches: ["main"]
    branches-ignore: ['ignore']


jobs:
  build:
    #the type of runner that that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, World This is in ubuntu

      - name: Second step
        run: |
          echo THis is second step

  build-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is a second Independent DB



  #job 2 with steps to echo " build-db"    
  build-db:
    needs: build
    runs-on: windows-latest

    steps:
      - run: echo "In Built-DB"
 
  #job 3 with steps to echo " build-db"
  package:
    needs: [build-app, build-db]
    runs-on: self-hosted
    steps:
      - name: This is 3 rd job
        run: |
          echo "THis is a new job in Self-hosted"










